### ISSUE TITLE
Error at FinishedJobEvent

### ISSUE THREAD

**Issue by galangbuana26** [yogameleniawan/laravel-queue-realtime-progress#2]
Hello, i found error at FinishedJobEvent, i currently using laravel 10. is it because my pusher settings or anything else?

`ArgumentCountError: Too few arguments to function YogaMeleniawan\JobBatchingWithRealtimeProgress\Events\FinishedJobEvent::__construct(), 1 passed in C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\yogameleniawan\realtime-job-batching\src\Jobs\FinishedJob.php on line 38 and exactly 5 expected in C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\yogameleniawan\realtime-job-batching\src\Events\FinishedJobEvent.php:24
Stack trace:
#0 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\yogameleniawan\realtime-job-batching\src\Jobs\FinishedJob.php(38): YogaMeleniawan\JobBatchingWithRealtimeProgress\Events\FinishedJobEvent->__construct(true)
#1 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): YogaMeleniawan\JobBatchingWithRealtimeProgress\Jobs\FinishedJob->handle()
#2 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#3 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#4 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#5 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Container\Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#6 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#7 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(144): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(YogaMeleniawan\JobBatchingWithRealtimeProgress\Jobs\FinishedJob))
#8 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(YogaMeleniawan\JobBatchingWithRealtimeProgress\Jobs\FinishedJob))
#9 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#10 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow(Object(YogaMeleniawan\JobBatchingWithRealtimeProgress\Jobs\FinishedJob), false)
#11 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(YogaMeleniawan\JobBatchingWithRealtimeProgress\Jobs\FinishedJob))
#12 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(YogaMeleniawan\JobBatchingWithRealtimeProgress\Jobs\FinishedJob))
#13 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(126): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\DatabaseJob), Object(YogaMeleniawan\JobBatchingWithRealtimeProgress\Jobs\FinishedJob))
#15 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(102): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#16 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(439): Illuminate\Queue\Jobs\Job->fire()
#17 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(389): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#18 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(176): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#19 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(138): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#20 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(121): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#21 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#22 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#24 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#25 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Container\Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#26 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Console\Command.php(211): Illuminate\Container\Container->call(Array)
#27 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\symfony\console\Command\Command.php(326): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#28 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Console\Command.php(181): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#29 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\symfony\console\Application.php(1096): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\symfony\console\Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\symfony\console\Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(201): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 C:\Users\COMPUTER\Documents\Works\Laporand\Laravel\accounting.laporand\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 {main}`

**Comment by yogameleniawan** [comment]
@galangbuana26, thanks for reporting this issue! I believe the problem was caused by the arguments parameter in FinishedJobEvent.php. However, this issue has been fixed recently in the latest update. You can check out the fix at  [v1.1.2](https://github.com/yogameleniawan/laravel-queue-realtime-progress/releases/tag/v1.1.2 )

**Comment by galangbuana26** [comment]
it works! thanks for your help!
